bug: Fixes prepublish script in coc plugin
wix/import-cost pull request #172
Opened 2020-05-25 20:04 UTC by anshulguleria

Fixed the typo in prepublish script in coc-import-cost plugin.

Tested by locally installing the plugin. It was not creating `lib`
directory earlier but after fixing the typo it stated working

2021-01-12 07:24 UTC, anshulguleria commented
Hi,

Any update on this? This seems to be still pending. If there is anything else I need to add let me know.

2021-01-12 17:57 UTC, yairhaimo commented
Hi. Sorry for the lack of response. I put a whole week aside (starting from January 24th) to work on this project. I hope it can wait until then.

2021-01-15 09:09 UTC, anshulguleria commented
Sure, no problem. Thanks for updating though.

2021-01-26 13:05 UTC, yairhaimo requested changes

2021-01-26 13:05 UTC, yairhaimo commented on package.json
> +    "postinstall": "lerna link && lerna exec -- npm i && lerna bootstrap --loglevel verbose",
`lerna bootstrap` already runs `npm install` and links all the packages, no need to run them explictly.

2021-01-26 13:06 UTC, yairhaimo commented
Hi. I made some changes in the `vscode` extension, please sync with origin, update the PR and ill merge.
Thanks!

2022-03-12 12:09 UTC, shahata commented
update. thanks!

2022-03-12 12:09 UTC, closed without merging